CREATE DATABASE BIZZBUZZ;
USE BIZZBUZZ;

-- Create USER Table
CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    NAME VARCHAR(100),
    PHONE_NO VARCHAR(15),
    ADDRESS TEXT,
    USER_TYPE ENUM('Buyer', 'Seller', 'Admin') NOT NULL
);

-- Create PRODUCT Table
CREATE TABLE PRODUCT (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INT NOT NULL,
    DESCRIPTION VARCHAR(5000),
    PRICE DECIMAL(10, 2) NOT NULL,
    AVAILABLE INT,
    NAME VARCHAR(100) NOT NULL,
    PICTURE LONGBLOB,
    SELLER_ID INT,
    FOREIGN KEY (SELLER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- Create REVIEWS Table
CREATE TABLE REVIEWS (
    REVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
    REVIEW_DATE DATE NOT NULL,
    STAR_RATING DECIMAL(2, 1) CHECK (STAR_RATING BETWEEN 1.0 AND 5.0),
    REVIEW_TEXT TEXT,
    BUYER_ID INT,
    PRODUCT_ID INT,
    FOREIGN KEY (BUYER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE
);

-- Create COMPLAINT Table
CREATE TABLE COMPLAINT (
    COMPLAINT_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT,
    BUYER_ID INT,
    ADMIN_ID INT,
    FOREIGN KEY (BUYER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ADMIN_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- Create CART Table
CREATE TABLE CART (
    CART_ID INT AUTO_INCREMENT PRIMARY KEY,
    CHECKOUT_DATE DATE,
    BUYER_ID INT,
    FOREIGN KEY (BUYER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- Create CART_PRODUCT_JUNCTION Table
CREATE TABLE CART_PRODUCT_JUNCTION (
    CHECKOUT_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUANTITY INT NOT NULL,
    PRODUCT_ID INT,
    CART_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID) ON DELETE CASCADE
);

-- Create CHECK_OUT Table
CREATE TABLE CHECK_OUT (
    CHECKOUT_ID INT AUTO_INCREMENT PRIMARY KEY,
	CHECKOUT_DATE DATETIME NOT NULL,
     CART_ID INT,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID) ON DELETE CASCADE
);